---
- name: Wait for instance ready
  gather_facts: false
  hosts: all
  tasks:
    - name: Ping SSH port
      ansible.builtin.wait_for:
        host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
        port: 22
        delay: 1
        timeout: 300
      delegate_to: localhost

- name: Approve SSH fingerprint
  gather_facts: false
  hosts: all
  tasks:
    - name: Check known_hosts for
      ansible.builtin.command: ssh-keygen -F {{ inventory_hostname }}
      register: check_entry_in_known_hosts
      failed_when: false
      changed_when: false
      ignore_errors: true
      delegate_to: localhost
    - name: Skip question for adding host key
      ansible.builtin.set_fact:
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      when: check_entry_in_known_hosts.rc == 1
    - name: Add SSH fingerprint to known host
      ansible.builtin.setup:
      when: check_entry_in_known_hosts.rc == 1

- name: Install Clickhouse
  hosts: clickhouse
  vars:
    clickhouse_version: "22.3.3.44"
    clickhouse_listen_host:
      - "::"
    clickhouse_dbs_custom:
      - { name: "logs" }
    clickhouse_profiles_default:
      default:
        date_time_input_format: best_effort
    clickhouse_users_custom:
      - { name: "user",
          password: "userlog",
          profile: "default",
          quota: "default",
          networks: { '::/0' },
          dbs: ["logs"],
          access_management: 0 }
    file_log_structure: "file String, host String, message String, timestamp DateTime64"
  roles:
    - clickhouse-role
  post_tasks:
    - name: Create tables
      ansible.builtin.command: "clickhouse-client --host 127.0.0.1 -q 'CREATE TABLE logs.file_log ({{ file_log_structure }}) ENGINE = Log();'"
      register: create_tbl
      failed_when: create_tbl.rc != 0 and create_tbl.rc != 57
      changed_when: create_tbl.rc == 0

- name: Install Vector
  hosts: vector
  vars:
    vector_test_dir: "/home/{{ ansible_user }}/test"
    clickhouse_host: "{{ hostvars[groups['clickhouse'][0]]['ansible_host'] }}"
    clickhouse_user: "user"
    clickhouse_password: "userlog"
  roles:
    - vector-role

- name: Install Lighthouse
  hosts: lighthouse
  vars:
    lighthouse_path: "/usr/share/nginx/lighthouse"
    lighthouse_port: "8008"
    clickhouse_host: "{{ hostvars[groups['clickhouse'][0]]['ansible_host'] }}"
    clickhouse_user: "user"
    clickhouse_password: "userlog"
  roles:
    - lighthouse-role
...
